langauge: python

python:
  - "3.4.3"
  - "3.6.7"
  - "2.7.6"

sudo: enabled

before_script:
  - pip install distribute
  - pip install -r requirements.txt

script:
  - python3 -m pytest --cov=app tests/

after_success:
  - coveralls
